/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.ejb.remote.database.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import ru.uvuv643.ejb.remote.database.tables.TeamHeroes;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamHeroesRecord extends UpdatableRecordImpl<TeamHeroesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.team_heroes.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.team_heroes.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.team_heroes.hero_id</code>.
     */
    public void setHeroId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.team_heroes.hero_id</code>.
     */
    public Integer getHeroId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TeamHeroes.TEAM_HEROES.TEAM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TeamHeroes.TEAM_HEROES.HERO_ID;
    }

    @Override
    public Integer component1() {
        return getTeamId();
    }

    @Override
    public Integer component2() {
        return getHeroId();
    }

    @Override
    public Integer value1() {
        return getTeamId();
    }

    @Override
    public Integer value2() {
        return getHeroId();
    }

    @Override
    public TeamHeroesRecord value1(Integer value) {
        setTeamId(value);
        return this;
    }

    @Override
    public TeamHeroesRecord value2(Integer value) {
        setHeroId(value);
        return this;
    }

    @Override
    public TeamHeroesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamHeroesRecord
     */
    public TeamHeroesRecord() {
        super(TeamHeroes.TEAM_HEROES);
    }

    /**
     * Create a detached, initialised TeamHeroesRecord
     */
    public TeamHeroesRecord(Integer teamId, Integer heroId) {
        super(TeamHeroes.TEAM_HEROES);

        setTeamId(teamId);
        setHeroId(heroId);
    }
}
