/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.database;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.car_id_seq</code>
     */
    public static final Sequence<Integer> CAR_ID_SEQ = Internal.createSequence("car_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.coordinates_id_seq</code>
     */
    public static final Sequence<Integer> COORDINATES_ID_SEQ = Internal.createSequence("coordinates_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.humanbeing_id_seq</code>
     */
    public static final Sequence<Long> HUMANBEING_ID_SEQ = Internal.createSequence("humanbeing_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
