/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.database;


import ru.uvuv643.database.tables.Car;
import ru.uvuv643.database.tables.Coordinates;
import ru.uvuv643.database.tables.Humanbeing;
import ru.uvuv643.database.tables.TeamHeroes;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.car</code>.
     */
    public static final Car CAR = Car.CAR;

    /**
     * The table <code>public.coordinates</code>.
     */
    public static final Coordinates COORDINATES = Coordinates.COORDINATES;

    /**
     * The table <code>public.humanbeing</code>.
     */
    public static final Humanbeing HUMANBEING = Humanbeing.HUMANBEING;

    /**
     * The table <code>public.team_heroes</code>.
     */
    public static final TeamHeroes TEAM_HEROES = TeamHeroes.TEAM_HEROES;
}
