/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.database.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import ru.uvuv643.database.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Mood implements EnumType {

    SORROW("SORROW"),

    APATHY("APATHY"),

    CALM("CALM"),

    RAGE("RAGE"),

    FRENZY("FRENZY");

    private final String literal;

    private Mood(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "mood";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
