/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.database.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import ru.uvuv643.database.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum WeaponType implements EnumType {

    HAMMER("HAMMER"),

    AXE("AXE"),

    PISTOL("PISTOL"),

    KNIFE("KNIFE"),

    BAT("BAT");

    private final String literal;

    private WeaponType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "weapon_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
