/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.ejb.remote.database;


import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import ru.uvuv643.ejb.remote.database.tables.Car;
import ru.uvuv643.ejb.remote.database.tables.Coordinates;
import ru.uvuv643.ejb.remote.database.tables.Humanbeing;
import ru.uvuv643.ejb.remote.database.tables.TeamHeroes;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.car</code>.
     */
    public final Car CAR = Car.CAR;

    /**
     * The table <code>public.coordinates</code>.
     */
    public final Coordinates COORDINATES = Coordinates.COORDINATES;

    /**
     * The table <code>public.humanbeing</code>.
     */
    public final Humanbeing HUMANBEING = Humanbeing.HUMANBEING;

    /**
     * The table <code>public.team_heroes</code>.
     */
    public final TeamHeroes TEAM_HEROES = TeamHeroes.TEAM_HEROES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CAR_ID_SEQ,
            Sequences.COORDINATES_ID_SEQ,
            Sequences.HUMANBEING_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Car.CAR,
            Coordinates.COORDINATES,
            Humanbeing.HUMANBEING,
            TeamHeroes.TEAM_HEROES);
    }
}
