/*
 * This file is generated by jOOQ.
 */
package ru.uvuv643.database.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import ru.uvuv643.database.enums.Mood;
import ru.uvuv643.database.enums.WeaponType;
import ru.uvuv643.database.tables.Humanbeing;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HumanbeingRecord extends UpdatableRecordImpl<HumanbeingRecord> implements Record11<Long, String, Integer, LocalDate, Boolean, Boolean, Double, Double, WeaponType, Mood, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.humanbeing.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.humanbeing.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.humanbeing.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.humanbeing.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.humanbeing.coordinates_id</code>.
     */
    public void setCoordinatesId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.humanbeing.coordinates_id</code>.
     */
    public Integer getCoordinatesId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.humanbeing.creationdate</code>.
     */
    public void setCreationdate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.humanbeing.creationdate</code>.
     */
    public LocalDate getCreationdate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.humanbeing.realhero</code>.
     */
    public void setRealhero(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.humanbeing.realhero</code>.
     */
    public Boolean getRealhero() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.humanbeing.hastoothpick</code>.
     */
    public void setHastoothpick(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.humanbeing.hastoothpick</code>.
     */
    public Boolean getHastoothpick() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.humanbeing.impactspeed</code>.
     */
    public void setImpactspeed(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.humanbeing.impactspeed</code>.
     */
    public Double getImpactspeed() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.humanbeing.minutesofwaiting</code>.
     */
    public void setMinutesofwaiting(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.humanbeing.minutesofwaiting</code>.
     */
    public Double getMinutesofwaiting() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.humanbeing.weapontype</code>.
     */
    public void setWeapontype(WeaponType value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.humanbeing.weapontype</code>.
     */
    public WeaponType getWeapontype() {
        return (WeaponType) get(8);
    }

    /**
     * Setter for <code>public.humanbeing.mood</code>.
     */
    public void setMood(Mood value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.humanbeing.mood</code>.
     */
    public Mood getMood() {
        return (Mood) get(9);
    }

    /**
     * Setter for <code>public.humanbeing.car_id</code>.
     */
    public void setCarId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.humanbeing.car_id</code>.
     */
    public Integer getCarId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, Integer, LocalDate, Boolean, Boolean, Double, Double, WeaponType, Mood, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, Integer, LocalDate, Boolean, Boolean, Double, Double, WeaponType, Mood, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Humanbeing.HUMANBEING.ID;
    }

    @Override
    public Field<String> field2() {
        return Humanbeing.HUMANBEING.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Humanbeing.HUMANBEING.COORDINATES_ID;
    }

    @Override
    public Field<LocalDate> field4() {
        return Humanbeing.HUMANBEING.CREATIONDATE;
    }

    @Override
    public Field<Boolean> field5() {
        return Humanbeing.HUMANBEING.REALHERO;
    }

    @Override
    public Field<Boolean> field6() {
        return Humanbeing.HUMANBEING.HASTOOTHPICK;
    }

    @Override
    public Field<Double> field7() {
        return Humanbeing.HUMANBEING.IMPACTSPEED;
    }

    @Override
    public Field<Double> field8() {
        return Humanbeing.HUMANBEING.MINUTESOFWAITING;
    }

    @Override
    public Field<WeaponType> field9() {
        return Humanbeing.HUMANBEING.WEAPONTYPE;
    }

    @Override
    public Field<Mood> field10() {
        return Humanbeing.HUMANBEING.MOOD;
    }

    @Override
    public Field<Integer> field11() {
        return Humanbeing.HUMANBEING.CAR_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCoordinatesId();
    }

    @Override
    public LocalDate component4() {
        return getCreationdate();
    }

    @Override
    public Boolean component5() {
        return getRealhero();
    }

    @Override
    public Boolean component6() {
        return getHastoothpick();
    }

    @Override
    public Double component7() {
        return getImpactspeed();
    }

    @Override
    public Double component8() {
        return getMinutesofwaiting();
    }

    @Override
    public WeaponType component9() {
        return getWeapontype();
    }

    @Override
    public Mood component10() {
        return getMood();
    }

    @Override
    public Integer component11() {
        return getCarId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCoordinatesId();
    }

    @Override
    public LocalDate value4() {
        return getCreationdate();
    }

    @Override
    public Boolean value5() {
        return getRealhero();
    }

    @Override
    public Boolean value6() {
        return getHastoothpick();
    }

    @Override
    public Double value7() {
        return getImpactspeed();
    }

    @Override
    public Double value8() {
        return getMinutesofwaiting();
    }

    @Override
    public WeaponType value9() {
        return getWeapontype();
    }

    @Override
    public Mood value10() {
        return getMood();
    }

    @Override
    public Integer value11() {
        return getCarId();
    }

    @Override
    public HumanbeingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public HumanbeingRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public HumanbeingRecord value3(Integer value) {
        setCoordinatesId(value);
        return this;
    }

    @Override
    public HumanbeingRecord value4(LocalDate value) {
        setCreationdate(value);
        return this;
    }

    @Override
    public HumanbeingRecord value5(Boolean value) {
        setRealhero(value);
        return this;
    }

    @Override
    public HumanbeingRecord value6(Boolean value) {
        setHastoothpick(value);
        return this;
    }

    @Override
    public HumanbeingRecord value7(Double value) {
        setImpactspeed(value);
        return this;
    }

    @Override
    public HumanbeingRecord value8(Double value) {
        setMinutesofwaiting(value);
        return this;
    }

    @Override
    public HumanbeingRecord value9(WeaponType value) {
        setWeapontype(value);
        return this;
    }

    @Override
    public HumanbeingRecord value10(Mood value) {
        setMood(value);
        return this;
    }

    @Override
    public HumanbeingRecord value11(Integer value) {
        setCarId(value);
        return this;
    }

    @Override
    public HumanbeingRecord values(Long value1, String value2, Integer value3, LocalDate value4, Boolean value5, Boolean value6, Double value7, Double value8, WeaponType value9, Mood value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HumanbeingRecord
     */
    public HumanbeingRecord() {
        super(Humanbeing.HUMANBEING);
    }

    /**
     * Create a detached, initialised HumanbeingRecord
     */
    public HumanbeingRecord(Long id, String name, Integer coordinatesId, LocalDate creationdate, Boolean realhero, Boolean hastoothpick, Double impactspeed, Double minutesofwaiting, WeaponType weapontype, Mood mood, Integer carId) {
        super(Humanbeing.HUMANBEING);

        setId(id);
        setName(name);
        setCoordinatesId(coordinatesId);
        setCreationdate(creationdate);
        setRealhero(realhero);
        setHastoothpick(hastoothpick);
        setImpactspeed(impactspeed);
        setMinutesofwaiting(minutesofwaiting);
        setWeapontype(weapontype);
        setMood(mood);
        setCarId(carId);
    }
}
